### PR TITLE
Added Extended Segment Address and Extended Linear Address records to…

### PR DESCRIPTION
**Pull request by welash**
… the

intel hex reader, and use Extended Linear Address records in the intel hex
writer when dealing with addresses greater the 64k

This may help with issue #36 if the reporter was using an intel hex file to do the writing.

### CODE REVIEW

**Comment by spth** [comment]
I noticed that when using stm8flash on Debian GNU/Linux with Intel hex files from various compilers:
SDCC on GNU/Linux - just works
Cosmic on Windows - hex file needs to be passed through dos2unix
IAR and Raisonance on Windows - hex file needs to be passed through objcopy -I ihex -O ihex and dos2unix

If I omit the dos2unix, Iget a read error in stm8flash. If I omit the objcopy, I get wrong data written to the device.

Does this merge request help fix those issues?

Philipp

**Comment by welash** [comment]
I don't think it will help with the dos2unix part.  That sounds like the stm8flash ihex reader isn't ignoring the line ending.  I can take a look at that and (probably) fix it.  I can't be sure about objcopy issue.  If you have an example of the hex file I can look at it.  It is possible that they are putting on an Extended Segment Address record at the start and using addresses that are relative to that, and the objcopy fixes that.  In that case, this change may fix having to run it through objcopy.  It you see a short record at the beginning that looks like ":LL000002YYYYXX" (the key part being the 02 in the record type field, and the YYYY being something other than 0000, then there is an ESA record.  I could imagine that they might put in a record that offsets to the base address of the section they are writing.

**Comment by spth** [comment]
I had a quick look at the issue. And it turned out that it had nothing to do with what objcopy really does. It's just the filename. stm8flash expects .ihx, while some tools output .hex or .HEX. And wheninvoking objcopy I chose an .ihx file for output.
So the line ending is the only real issue.

Philipp

**Comment by welash** [comment]
Ok, that makes sense.  I'll take a look at the CRLF issue this evening and try to update the pull request.  It probably would make sense if the hex file versus binary file were specified as an argument instead of inferring from the file name.

**Comment by welash** [comment]
Updated to strip trailing carriage return, and to make sure the buffer was big enough to handle any legal record.

**Comment by janezNov** [comment]
Writing solved with #65

**Pull request merged**
