### PR TITLE
1) Add unlock function 2) add precompiled windows binary

### PR DESCRIPTION
**Pull request by cpldcpu**
1) Added function '-u" to unlock devices with activated write protection. Many of the cheap chinese STM8S board come with write protected MCU for some reasons. This eases unlocking them.

2) Added procompiled windows binary so people with windows don't have to install MSYS2 to compile this tool.

### CODE REVIEW

**Comment by vdudouyt** [comment]
Sorry, but I really would like to avoid placing any executables in this Git repository. Could you send me another pull request without that .exe file so that I could put it in the releases section separately?

**Comment by cpldcpu** [comment]
No problem.

 - Exe removed
 - Added device specific ROP information as it appears that not all devices follow the same scheme. The unlock information is still undefined for many devices. An error will be thrown in that case.

**Comment by rpavlik** [comment]
FWIW, I have actually extracted (cherry-picked) just the commits here that add the ROP/unlock support (not including the commits that add or delete the .exe files, so they never enter the tree at all) into a branch here: https://github.com/rpavlik/stm8flash/tree/unlock-support

and an unrelated but useful commit into its own branch here: https://github.com/rpavlik/stm8flash/tree/error-msg-on-not-connected

Both are now on top of the latest master branch and merge cleanly.

I didn't make the contributions, so I feel like it's not really my place to pull request them, but @cpldcpu please feel free to take those branches and do so. (I made the branches for my own use in integrating your work and others into a "what I think is best" integration branch)

**Comment by cpldcpu** [comment]
I commend your effort - it seems that @vdudouyt has given up on his own creation.

So, how do we make sure that your fork is the one that will be found by people?

**Pull request merged**
