### PR TITLE
added serial, stm8L ROP handling

### PR DESCRIPTION
**Pull request by lkord**
stm8L ROP handling with no BROWNOUT settings
distinct serial for stlinksv2 fix

### CODE REVIEW

**Comment by spth** [comment]
IMO, "serial" could be confusing since it is a rather general term, and could e.g. refer to some serial protocol. This makes the code and help output harder to understand. I suggest to use that more clearly refers to a serial number (maybe use "serialno") instead.

Philipp

**Comment by lkord** [comment]
@spth what about "iSerial"? That is the descriptor from usb info

**Comment by spth** [comment]
We currently don't have camelCase variable names; I guess for the help output iSerial could be fine, while the variable could be i_serial or so.

Philipp

**Comment by spth** [comment]
Also, could you add your position on the license change (GPLv2 only vs. GPLv2 or later) in the file "LICENSE-CHANGE"?

Philipp

**Comment by lkord** [comment]
@spth Could You check this conflicting file? It is just the LICENSE file.

**Pull request merged**
