### PR TITLE
Debugger listing

### PR DESCRIPTION
**Pull request by schneidersoft**
Implement the short option -L to find and list all the interesting usb devices and serial numbers
correct some whitespace

### CODE REVIEW

**Comment by spth** [comment]
-L itself works for me. Even when I invoke it multiple times. But once I've invoked stm8flash otherwise, all serials are the same (example with an external ST/Link V2 and an STM8A-Discovery attached):

~~~~
root@notebook6:/tmp/stm8flash# ./stm8flash -L
Programmer 0: STMicroelectronics STM32 STLink, Serial Number:513F6B06493F50535320163F
Programmer 1: STMicroelectronics STM32 STLink, Serial Number:303030303030303030303031
root@notebook6:/tmp/stm8flash# ./stm8flash -L
Programmer 0: STMicroelectronics STM32 STLink, Serial Number:513F6B06493F50535320163F
Programmer 1: STMicroelectronics STM32 STLink, Serial Number:303030303030303030303031
root@notebook6:/tmp/stm8flash# ./stm8flash -c stlinkv2 -w /home/philipp/sdcc-trunk/sdcc-extra/historygraphs/dhrystone-stm8-speed-13900/image.ihx -p stm8af5288
Determine FLASH area
WARNING: More than one programmer found but no serial number given. Programmer 1 will be used:
Programmer 1: STMicroelectronics STM32 STLink, Serial Number:513F6B06493F50535320163F
Programmer 2: STMicroelectronics STM32 STLink, Serial Number:303030303030303030303031
STLink: v2, JTAG: v16, SWIM: v4, VID: 8304, PID: 4837
SWIM error 0x09
root@notebook6:/tmp/stm8flash# ./stm8flash -L
Programmer 0: STMicroelectronics STM32 STLink, Serial Number:303030303030303030303031
Programmer 1: STMicroelectronics STM32 STLink, Serial Number:303030303030303030303031
~~~~

**Comment by schneidersoft** [comment]
I was not able to reproduce the behavior you see. But I did find a minor bug in my implementation. It should not have caused what you are seeing though.

**Comment by spth** [comment]
As I have now learned the iSerial changing to 303030303030303030303031 after first use of the ST-Link/v2 is a known bug in ST-Link/v2 firmware that can be fixed with a firmware update.
Maybe we should emit a warning when we see a iSerial of 303030303030303030303031?

**Comment by schneidersoft** [comment]
I'd like to add a link to somewhere describing this bug. do you have a good link?

**Pull request merged**
