### PR TITLE
fixed compilation issue on windows

### PR DESCRIPTION
**Pull request by boseji**
Hi,
I had trouble with building this on windows.
So I fixed some parts of the make file and added some directives.
Hope this helps.

Regards,
@boseji

### CODE REVIEW

**Comment by janezNov** [comment]
What is the point of comments?
/* Modification @boseji <salearj@hotmail.com> 2017-08-04 */

**Comment by boseji** [comment]
Its just to help you knock out my changes if you do not want them.
I am still facing issues with driver detection on my older PCs for STLINK.
The normal driver work but the moment I switch the driver, it just does not get detected any more.
Not sure whats wrong, I am using Windows 10 and Windows 7 version both begin 64-bit.
Any suggestions would be very helpful.

In fact with this the possibility of having Arduino style system for STM8 becomes very real.

**Comment by boseji** [comment]
Thanks

**Comment by janezNov** [comment]
Why closed pull request? I did not have the time to check, but I am sure it works, just comment are in my experience not needed. No hard fillings!

**Pull request closed without merging**
